baseurl = "https://nicolasmorin.com"
theme = "PaperMod"
pagerSize = 10
Title = "Nicolas Morin ğŸ•¶"

[params]
  Title       = "Nicolas Morin ğŸ•¶"
  description = "RÃ©cits et fictions courtes, rhum, tech, thÃ©orie politique et Ã©thique."
  enableInlineShortcodes = "true"
  enableRobotsTXT = "true"
  buildDrafts = "true"
  buildFuture = "true"
  buildExpired = "true"
  enableEmoji = "true"
  pygmentsUseClasses = "true"
  mainsections = ["post"]
  social = "true"

[params.homeInfoParams]
  Title = "ğŸ‘‹"
  Content = """
Je rassemble ici des textes sur des sujets divers : 

  - ğŸ“š littÃ©rature (en particulier le genre de la nouvelle)
  - ğŸ—³ï¸ thÃ©orie politique et Ã©thique (en particulier Judith Shklar)
  - ğŸ¤– technologies
  - ğŸ¹ rhum et alcools
"""


[outputs]
  home = [ "HTML", "RSS", "JSON" ]



[[menu.main]]
  name = "Philosophie politique"
  url = "/tags/philosophie-politique/"
  weight = 210

[[menu.main]]
  name = "Alcool"
  url = "/tags/alcool/"
  weight = 220

[[menu.main]]
  name = "Divers"
  url = "/divers/"
  weight = 230

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

ignoreLogs = ['warning-goldmark-raw-html']